// Retain form nodes and their draft contracts while arranging the shared studio shell.
(()=>{
 const q=s=>document.querySelector(s),make=(tag,cls,html)=>{const n=document.createElement(tag);n.className=cls;n.innerHTML=html;return n;};
 const background=make('div','studio-background','<img id="studio-wallpaper" alt=""><div></div>');background.setAttribute('aria-hidden','true');document.body.prepend(background);
 const voice=q('#page-voice'),ready=q('#voice-ready'),layout=voice.querySelector('.cover-layout'),cards=[...layout.querySelector('.cover-main').children];
 const heading=make('div','workbench-heading','<div class="workbench-heading-title"><span class="workspace-name">音色 Cover</span><span class="heading-slash">/</span></div><div class="workbench-heading-actions"></div>');
 heading.firstChild.append(q('#voice-title'));heading.lastChild.append(q('#voice-draft-status'),q('#voice-generate'));voice.querySelector('.page-heading').replaceWith(heading);
 const intro=make('div','voice-intro','<p>保留歌词、旋律与演唱节奏，换成你选择的声音。</p>');intro.append(ready);heading.after(intro);
 const inputs=make('div','voice-input-grid','');for(const card of cards.slice(0,2))inputs.append(card);
 const settings=layout.querySelector('.cover-side .cover-card'),tuning=make('section','cover-card voice-tuning','<div class="section-top"><strong>演唱与混音</strong><span class="muted small">0 半音保留原调</span></div><div class="voice-tuning-fields"></div><div class="voice-tuning-footer"></div>');
 for(const id of ['voice-pitch','voice-pitch-mode']){const input=q('#'+id),label=input.previousElementSibling,field=make('div','','');field.append(label,input);tuning.querySelector('.voice-tuning-fields').append(field);}
 for(const label of cards[2].querySelectorAll('.voice-gains>label'))tuning.querySelector('.voice-tuning-fields').append(label);
 tuning.querySelector('.voice-tuning-footer').append(q('#voice-dynamics').closest('label'),q('#voice-generate-hint'));
 const tip=make('p','help voice-tuning-tip','变调会改变音高；仅换音色时保持 0。单人干声参考更清晰，建议先用 10–15 秒试听。');tuning.append(tip);
 layout.replaceWith(inputs,tuning);voice.classList.add('voice-workspace');
 for(const audio of document.querySelectorAll('audio')){audio.controls=false;audio.hidden=true;}
 for(const [id,label] of [['voice-original','试听原唱'],['voice-output','试听新音色'],['voice-vocal-preview','试听纯人声'],['cover-original','试听原片段'],['cover-output','试听 Cover']]){
  const audio=q('#'+id),button=make('button','button secondary audition-button','<i data-icon="play"></i><span>'+label+'</span>');button.dataset.listen=id;audio.after(button);
 }
 // The legacy player retains its audio and export hooks, without a second visible transport.
 q('#player').classList.add('legacy-player');
 for(const selector of ['#queue-list','#cover-history','#voice-history']){const n=q(selector);n.closest('.queue-section,.workbench-history').classList.add('legacy-queue');}
 document.body.append(make('section','studio-player',`<div class="now-playing"><div class="record-art"><i data-icon="music"></i></div><div><strong id="global-title">选择一首作品，开始试听</strong><span id="global-detail">音乐、原曲、参考声音与乐谱共用此播放器</span></div></div><div class="global-transport"><div class="global-buttons"><button id="global-loop" class="icon-button" aria-label="循环播放" aria-pressed="false"><i data-icon="repeat"></i></button><button id="global-prev" class="icon-button" aria-label="上一首作品"><i data-icon="player-track-prev"></i></button><button id="global-play" class="global-play" aria-label="播放" disabled><i data-icon="player-play"></i></button><button id="global-next" class="icon-button" aria-label="下一首作品"><i data-icon="player-track-next"></i></button><button id="global-stop" class="icon-button" aria-label="停止播放" disabled><i data-icon="player-stop"></i></button></div><div class="global-timeline"><span id="global-current">0:00</span><input id="global-seek" type="range" min="0" max="1" step="0.01" value="0" aria-label="播放进度" disabled><span id="global-duration">0:00</span></div></div><div class="global-extras"><button id="global-export" class="text-button" disabled>导出</button><button id="global-mute" class="icon-button" aria-label="静音" aria-pressed="false"><i data-icon="volume"></i></button><input id="global-volume" type="range" min="0" max="1" step="0.01" value="1" aria-label="播放器音量"><button id="global-queue" class="icon-button" aria-label="展开任务队列" aria-controls="task-drawer" aria-expanded="false"><i data-icon="playlist"></i><span id="global-task-count">0</span></button></div>`));
 document.body.append(make('aside','task-shelf',`<button id="task-handle" aria-controls="task-drawer" aria-expanded="false"><i data-icon="playlist"></i><span>任务</span><b id="task-count">0</b></button><section id="task-drawer" aria-label="本地任务队列" hidden><div class="task-heading"><div><strong>任务队列</strong><p id="task-summary">本机任务与生成记录</p></div><button id="task-pin" class="icon-button" aria-label="固定任务栏" aria-pressed="false"><i data-icon="pinned"></i></button><button id="task-close" class="icon-button" aria-label="收起任务栏"><i data-icon="chevrons-right"></i></button></div><div class="task-filters"><button data-task-filter="active" aria-pressed="true">进行中</button><button data-task-filter="all" aria-pressed="false">全部记录</button></div><div id="task-items"></div><div class="task-footer">所有音频任务共用单显卡，按顺序执行</div></section>`));
 const appearance=make('section','appearance-card',`<div class="section-top"><div><strong>外观与背景</strong><p>选一个喜欢的色调，把工作室变成你的空间。</p></div><span id="appearance-status" class="muted small" role="status">设置保存在本机</span></div><div class="theme-presets"><button data-theme="classic" aria-pressed="true"><span class="theme-swatch swatch-classic"></span><strong>经典工作室</strong><small>炭黑 · 浅绿</small></button><button data-theme="dark" aria-pressed="false"><span class="theme-swatch swatch-dark"></span><strong>深海夜色</strong><small>深蓝 · 湖蓝</small></button><button data-theme="light" aria-pressed="false"><span class="theme-swatch swatch-light"></span><strong>晴日留白</strong><small>暖白 · 云红</small></button></div><div class="appearance-options"><label>强调色<input id="appearance-accent" type="color" value="#d4edaa"></label><label>背景遮罩 <output id="appearance-overlay-value">72%</output><input id="appearance-overlay" type="range" min="35" max="95" value="72"></label><label>背景模糊 <output id="appearance-blur-value">4px</output><input id="appearance-blur" type="range" min="0" max="24" value="4"></label><div class="background-actions"><button id="appearance-import" class="button secondary"><i data-icon="photo"></i>选择背景图片</button><button id="appearance-remove" class="text-button" disabled>移除背景</button></div></div><p class="help">PNG / JPG / WebP，最大 20MB。图片保存在本机，重启后自动恢复。乐谱保持白纸样式，便于编辑与打印。</p>`);
 q('#page-settings .page-heading').after(appearance);
})();
