'use strict';
class VoiceRegion{
 constructor(kind){
  this.kind=kind;this.audio=$(`#voice-${kind}-audio`);const prefix=kind==='source'?'voice-':'voice-reference-';this.start=$('#'+prefix+'start');this.end=$('#'+prefix+'end');this.peaks=null;this.key=null;this.generation=0;
  this.track=document.createElement('div');this.track.className='voice-region';this.track.tabIndex=0;this.track.setAttribute('role','slider');this.track.setAttribute('aria-label',kind==='source'?'原曲播放位置':'参考声音播放位置');
  this.track.innerHTML='<canvas aria-hidden="true"></canvas><div class="region-selection" tabindex="0" role="group" aria-label="移动音频选段"><button class="region-handle" data-edge="start" role="slider" aria-label="选段起点"></button><button class="region-handle" data-edge="end" role="slider" aria-label="选段终点"></button></div><div class="region-playhead"></div><span class="region-message" role="status">选择声音后显示波形</span>';
  this.audio.before(this.track);this.help=document.createElement('div');this.help.className='region-help';this.help.innerHTML='<span>点击定位 · 拖动两端裁剪 · 拖选区移动</span><button class="text-button" hidden>重载波形</button>';this.track.after(this.help);this.help.querySelector('button').onclick=()=>{this.key=null;this.load();};
  this.canvas=this.track.querySelector('canvas');this.selection=this.track.querySelector('.region-selection');this.message=this.track.querySelector('.region-message');
  for(const event of ['loadedmetadata','emptied'])this.audio.addEventListener(event,()=>this.load());for(const event of ['timeupdate','seeking'])this.audio.addEventListener(event,()=>this.paint());
  for(const input of [this.start,this.end])input.addEventListener('input',()=>{studioPlayer.clearClip(this.audio);this.paint();});
  this.track.onpointerdown=e=>{if(e.button!==0||!this.duration)return;this.track.setPointerCapture(e.pointerId);this.drag={x:e.clientX,at:this.at(e),start:Number(this.start.value),end:Number(this.end.value),mode:e.target.dataset.edge||(e.target.closest('.region-selection')?'move':'seek')};};
  this.track.onpointermove=e=>{if(!this.drag)return;const d=this.drag,at=this.at(e),delta=at-d.at,min=Math.min(5,this.duration),max=this.kind==='source'?300:25;let s=d.start,t=d.end;
   if(d.mode==='start')s=Math.max(0,Math.min(t-min,Math.max(t-max,at)));else if(d.mode==='end')t=Math.min(this.duration,Math.max(s+min,Math.min(s+max,at)));else if(d.mode==='move'){s=Math.max(0,Math.min(this.duration-(t-s),s+delta));t=s+(d.end-d.start);}else if(Math.abs(e.clientX-d.x)>4){s=Math.min(d.at,at);t=Math.min(this.duration,Math.max(d.at,at));t=Math.min(s+max,Math.max(s+min,t));if(t>this.duration){t=this.duration;s=Math.max(0,t-min);}}
   this.set(s,t,false);
  };
  this.track.onpointerup=e=>{if(!this.drag)return;const d=this.drag;this.drag=null;if(this.track.hasPointerCapture(e.pointerId))this.track.releasePointerCapture(e.pointerId);if(Math.abs(e.clientX-d.x)<4&&d.mode==='seek'){studioPlayer.clearClip(this.audio);studioPlayer.select(this.audio);this.audio.currentTime=this.at(e);}else this.commit();};
  const cancel=()=>{if(this.drag){this.set(this.drag.start,this.drag.end,false);this.drag=null;}};this.track.onpointercancel=cancel;this.track.onlostpointercapture=cancel;
  this.track.onkeydown=e=>{if(!this.duration||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const edge=e.target.dataset.edge,delta=(e.shiftKey?1:.1)*(e.key==='ArrowLeft'?-1:1),min=Math.min(5,this.duration),max=this.kind==='source'?300:25;let s=Number(this.start.value),t=Number(this.end.value);
   if(edge==='start')s=Math.min(t-min,Math.max(0,t-max,e.key==='Home'?0:e.key==='End'?t-min:s+delta));else if(edge==='end')t=Math.max(s+min,Math.min(this.duration,s+max,e.key==='Home'?s+min:e.key==='End'?this.duration:t+delta));else if(e.target===this.selection){const length=t-s;s=e.key==='Home'?0:e.key==='End'?this.duration-length:Math.min(this.duration-length,Math.max(0,s+delta));t=s+length;}else{studioPlayer.clearClip(this.audio);studioPlayer.select(this.audio);this.audio.currentTime=e.key==='Home'?0:e.key==='End'?this.duration:Math.max(0,Math.min(this.duration,this.audio.currentTime+delta));return;}this.set(s,t,true);
  };
  new ResizeObserver(()=>this.draw()).observe(this.track);this.paint();
 }
 get duration(){return studioPlayer.duration(this.audio);}
 at(e){const b=this.track.getBoundingClientRect();return Math.min(this.duration,Math.max(0,(e.clientX-b.left)/b.width*this.duration));}
 set(s,e,commit){this.start.value=s.toFixed(2);this.end.value=e.toFixed(2);this.paint();if(commit)this.commit();}
 commit(){studioPlayer.clearClip(this.audio);this.start.dispatchEvent(new Event('input',{bubbles:true}));this.end.dispatchEvent(new Event('input',{bubbles:true}));}
 paint(){const d=this.duration,s=Number(this.start.value),e=Number(this.end.value);this.selection.hidden=!d;this.selection.style.left=(d?s/d*100:0)+'%';this.selection.style.width=(d?(e-s)/d*100:0)+'%';this.track.querySelector('.region-playhead').style.left=(d?this.audio.currentTime/d*100:0)+'%';this.track.setAttribute('aria-valuemin','0');this.track.setAttribute('aria-valuemax',String(d));this.track.setAttribute('aria-valuenow',String(this.audio.currentTime||0));for(const b of this.selection.querySelectorAll('button')){b.setAttribute('aria-valuemin','0');b.setAttribute('aria-valuemax',String(d));b.setAttribute('aria-valuenow',String(b.dataset.edge==='start'?s:e));}this.help.querySelector('span').textContent=d?`选段 ${(e-s).toFixed(1)} 秒 · 拖动两端或选区调整`:'点击定位 · 拖动两端裁剪 · 拖选区移动';}
 async load(){const key=this.audio.getAttribute('src');if(key===this.key)return;this.key=key;const generation=++this.generation;this.peaks=null;this.message.hidden=false;this.message.textContent=key?'正在读取声音波形…':'选择声音后显示波形';this.help.querySelector('button').hidden=true;this.draw();if(!key)return;
  try{const url=new URL(key),result=await api.audioWaveform({kind:url.pathname==='/original.wav'?'source':'job',id:url.hostname});if(generation!==this.generation)return;this.peaks=result.peaks;this.message.hidden=true;this.draw();}catch(e){if(generation===this.generation){this.message.textContent='波形暂不可用，可输入时间并试听';this.help.querySelector('button').hidden=false;}}}
 draw(){const width=this.track.clientWidth,height=this.track.clientHeight,dpr=devicePixelRatio||1;if(!width)return;this.canvas.width=width*dpr;this.canvas.height=height*dpr;const ctx=this.canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,width,height);ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--muted');if(this.peaks?.length)for(let x=0;x<width;x+=2){const p=Math.max(0,...this.peaks.slice(Math.floor(x/width*this.peaks.length),Math.max(Math.floor(x/width*this.peaks.length)+1,Math.ceil((x+2)/width*this.peaks.length))));const h=Math.max(1,p*(height-16));ctx.fillRect(x,(height-h)/2,1,h);}else{ctx.globalAlpha=.3;ctx.fillRect(12,height/2,width-24,1);}this.paint();}
}
window.voiceRegions=['source','reference'].map(kind=>new VoiceRegion(kind));
